plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.3' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

subprojects {
    if (polylib_maven_url) {
        repositories {
            maven {
                name = 'PolyLib'
                url = uri(polylib_maven_url)
            }
        }
    }
    repositories {
        maven {
            name = 'BlameJared'
            url = uri('https://maven.blamejared.com')
        }
    }
}
