# Project
version=4.8.0
group=net.gigabit101.quantumstorage
java_version=25

# Common
minecraft_version=26.1.2
mod_name=QuantumStorage
mod_author=gigabit101
mod_id=quantumstorage
license=GPL-3.0-only
credits=
description=Store all the things.
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.151.0+26.1.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.1.2.76
neoforge_loader_version_range=[4,)

# PolyLib
polylib_maven_url=https://maven.creeperhost.net/
polylib_version=26.1.2-2.0.10
polylib_mod_version=2.0.10

# JEI
jei_minecraft_version=26.1.2
jei_version=29.6.2.38

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
