modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "quantumstorage.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "polylib"
type = "required"
versionRange = "[${polylib_mod_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"
